services:
  hotel_db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: hotel
      POSTGRES_PASSWORD: hotel_password
      POSTGRES_DB: hotels
    volumes:
      - hotel_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - external_bridge

  booking_db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking_password
      POSTGRES_DB: booking
    volumes:
      - booking_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - external_bridge

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - external_bridge

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_JMX_PORT=7071
      - KAFKA_JMX_HOSTNAME=kafka
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    ports:
      - "9092:9092"
      - "7071:7071"
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  jmx_exporter:
    image: bitnami/jmx-exporter:latest
    environment:
      - SERVICE_PORT=5556
    volumes:
      - ${PWD}/config/kafka/jmx_config.yml:/etc/jmx-exporter/config.yml
    command:
      - "5556"
      - "/etc/jmx-exporter/config.yml"
    ports:
      - "5556:5556"
    depends_on:
      - kafka
    networks:
      - kafka_network

  loki:
    image: grafana/loki:latest
    command:
      - --config.file=/etc/loki/local-config.yml
    volumes:
      - ${PWD}/config/loki.yml:/etc/loki/local-config.yml
      - loki_data:/loki/data
    ports:
      - "3100:3100"
    networks:
      - grafana_network

  tempo:
    image: grafana/tempo:latest
    command:
      - --config.file=/etc/tempo-config.yml
    volumes:
      - ${PWD}/config/tempo.yml:/etc/tempo-config.yml
      - tempo_data:/var/tempo
    ports:
      - "14268:14268" # jaeger
      - "3200:3200"   # tempo
      - "4317:4317"   # oltp grpc
    networks:
      - grafana_network

  alloy:
    image: grafana/alloy:latest
    restart: always
    user: root
    volumes:
      - ${PWD}/config/config.alloy:/etc/alloy/config.alloy:ro
      - /var/log/containers:/var/log/containers:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /var/log/journal:/var/log/journal:ro
      - /etc/hostname:/etc/hostname:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:9100
      - /etc/alloy/config.alloy
    ports:
      - "9100:9100"
    depends_on:
      - loki
      - prometheus
    networks:
      - grafana_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ${PWD}/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    ports:
      - "9090:9090"
    depends_on:
      - jmx_exporter
      - tempo
    networks:
      - kafka_network
      - grafana_network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ${PWD}/config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ${PWD}/config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ${PWD}/config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - grafana_network

volumes:
  hotel_data:
  booking_data:
  redis_data:
  prometheus_data:
  loki_data:
  tempo_data:

networks:
  grafana_network:
    driver: bridge
  kafka_network:
    driver: bridge
  external_bridge:
    driver: bridge
