services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_JMX_PORT=7071
      - KAFKA_JMX_HOSTNAME=kafka
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    ports:
      - "9092:9092"
      - "7071:7071"
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  init-topics:
    image: confluentinc/cp-kafka:7.7.0
    environment:
      BOOTSTRAP_SERVER: broker:9092
    volumes:
      - ${PWD}/scripts/init-topics.sh:/init-topics.sh:ro
    entrypoint: /init-topics.sh
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka_network

  jmx_exporter:
    image: bitnami/jmx-exporter:latest
    environment:
      - SERVICE_PORT=5556
    volumes:
      - ${PWD}/config/kafka/jmx_config.yml:/etc/jmx-exporter/config.yml
    command:
      - "5556"
      - "/etc/jmx-exporter/config.yml"
    ports:
      - "5556:5556"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
